### PR TITLE
MNIST & CIFAR training experimentation

### PR DESCRIPTION
**Pull request by aman-tiwari**
This change is [Reviewable](https://reviewable.io/reviews/pair-code/federated-learning/8)

---
experiments with seeing what it takes to get federated training working on a MNIST & CIFAR
.
Run with `cd experiments/mnist && ./reset_and_launch.sh NUM_CLIENTS NUM_EXAMPLES_PER_CLIENT ITERATIONS_BETWEEN_UPLOAD UPLOADS_BEFORE_AVG`
Also see the `grid_search.ts` script. 
The logs produced can be visualised using: https://beta.observablehq.com/@aman-tiwari/federated-learning-loss-vis

### CODE REVIEW

**Comment by aman-tiwari** [comment]
I thought the previous commits would be squashed when this branch was last merged in but I guess not (hence why so many)

**Comment by asross** [comment]
*[experiments/mnist/grid_search.ts, line 45 at r4](https://reviewable.io/reviews/pair-code/federated-learning/8#-LFxmGTF0Np4pdMkelqV:-LFxmGTF0Np4pdMkelqW:bn0xyxc) ([raw file](https://github.com/pair-code/federated-learning/blob/e6f50a24d23b739910b148cfa82a4b38e19cca41/experiments/mnist/grid_search.ts#L45)):*
> ```XML
>         done();
>       }
>     }, 500);
> ```

This is a cool pattern!

---


*Comments from [Reviewable](https://reviewable.io/reviews/pair-code/federated-learning/8)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: :shipit: complete! 1 of 1 LGTMs obtained

---

*[experiments/cifar/cifar_data.ts, line 32 at r4](https://reviewable.io/reviews/pair-code/federated-learning/8#-LG1TVPc2Xt3JldYTzfY:-LG1TVPc2Xt3JldYTzfZ:b-tfnlp7) ([raw file](https://github.com/pair-code/federated-learning/blob/e6f50a24d23b739910b148cfa82a4b38e19cca41/experiments/cifar/cifar_data.ts#L32)):*
> ```XML
> 
> const TRAIN_PATHS = [
>   './cifar-10-batches-bin/data_batch_1.bin',
> ```

checking these in is going to bloat the repo history, want to put them on GCP?

---

*[experiments/cifar/cifar_data.ts, line 77 at r4](https://reviewable.io/reviews/pair-code/federated-learning/8#-LG1Tbk54XRF39ZNufbH:-LG1Tbk54XRF39ZNufbI:b-pse5oy) ([raw file](https://github.com/pair-code/federated-learning/blob/e6f50a24d23b739910b148cfa82a4b38e19cca41/experiments/cifar/cifar_data.ts#L77)):*
> ```XML
>   }
> 
>   const img = new Uint8Array(numExamples * 3072);
> ```

32 * 32 * 3

---


*Comments from [Reviewable](https://reviewable.io/reviews/pair-code/federated-learning/8#-:-LG1VOIE4Pw9bXW6ynYs:b-jbsf8z)*

**Comment by aman-tiwari** [comment]
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---

*[experiments/cifar/cifar_data.ts, line 32 at r4](https://reviewable.io/reviews/pair-code/federated-learning/8#-LG1TVPc2Xt3JldYTzfY:-LG6IPQWAqDVc1MJyx7F:b-8r4nuy) ([raw file](https://github.com/pair-code/federated-learning/blob/e6f50a24d23b739910b148cfa82a4b38e19cca41/experiments/cifar/cifar_data.ts#L32)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

checking these in is going to bloat the repo history, want to put them on GCP?
</blockquote></details>

I added a script to download it from the official cifar website

---

*[experiments/cifar/cifar_data.ts, line 77 at r4](https://reviewable.io/reviews/pair-code/federated-learning/8#-LG1Tbk54XRF39ZNufbH:-LG6IUnNDqm_mf51Ypo6:bb6un1j) ([raw file](https://github.com/pair-code/federated-learning/blob/e6f50a24d23b739910b148cfa82a4b38e19cca41/experiments/cifar/cifar_data.ts#L77)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

32 * 32 * 3
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/pair-code/federated-learning/8)*

**Pull request merged**
