### PR TITLE
Defined message types & created communicator prototype that expects them

### PR DESCRIPTION
**Pull request by aman-tiwari**
First attempt at creating something that can upload and download variables and synchronize them with a server. WIP

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/federated-learning/3)

### CODE REVIEW

**Comment by dsmilkov** [comment]
Nice start!

---

Review status: 6 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/client/comm.ts, line 41 at r1](https://reviewable.io/reviews/pair-code/federated-learning/3#-LEMDE1lCYQNaJrQS3kX:-LEMDE1lCYQNaJrQS3kY:brs2fc0) ([raw file](https://github.com/pair-code/federated-learning/blob/080b6b748d83aad714f7eb653d9c98158aedb6d8/src/client/comm.ts#L41)):*
> ```XML
>  * await sync.uploadVars()
>  * ```
>  * The server->client synchronisation happens transparently whenever the server
> ```

would be better for the server to notify the client with the new weight, and let the client decide to accept/reject/postpone updating its model. That is, server->client sync shouldn't be transparent.

---


*Comments from [Reviewable](https://reviewable.io/reviews/pair-code/federated-learning/3#-:-LEME1Bx7mWU9_3jma3Q:br81ct)*

**Comment by aman-tiwari** [comment]
Review status: 6 of 7 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/client/comm.ts, line 38 at r1](https://reviewable.io/reviews/pair-code/federated-learning/3#-LEMBW3y88Kv8SKpnyOs:-LEMl4r6C5nnB42HjJn4:b-t3f1k2) ([raw file](https://github.com/pair-code/federated-learning/blob/080b6b748d83aad714f7eb653d9c98158aedb6d8/src/client/comm.ts#L38)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

high level comment -- can we not tie this to layers models? If you look at the sketch email from Daniel, maybe we can do this in a way that's specifically tied to individual tf.Tensors / tf.Variables instead of layers models.

WDYT?
</blockquote></details>

The constructor actually only takes a list of variables, the fromLayers is just a utility to construct one from layers - the example usage could be changed to reflect that

---

*[src/client/comm.ts, line 41 at r1](https://reviewable.io/reviews/pair-code/federated-learning/3#-LEMDE1lCYQNaJrQS3kX:-LEMlPVjCzl34zZgmiA_:b-j1n8v5) ([raw file](https://github.com/pair-code/federated-learning/blob/080b6b748d83aad714f7eb653d9c98158aedb6d8/src/client/comm.ts#L41)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

would be better for the server to notify the client with the new weight, and let the client decide to accept/reject/postpone updating its model. That is, server->client sync shouldn't be transparent.
</blockquote></details>

that makes sense but I thought we needed/wanted a global sync so we want all clients to upgrade at once (i.e when the server broadcasts weights) to the new federated averaging model so they can train on it and improve it. it could be worthwhile to let the client ask for/a promise that resolves at the next update rather than it be automatic. and if a global sync isn't needed then giving the client the control definitely seems good.

---


*Comments from [Reviewable](https://reviewable.io/reviews/pair-code/federated-learning/3)*

**Comment by asross** [comment]
Review status: 6 of 7 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/common.ts, line 30 at r1](https://reviewable.io/reviews/pair-code/federated-learning/3#-LEPbiab9_HfM7FEdUjn:-LEPbiab9_HfM7FEdUjo:b58drik) ([raw file](https://github.com/pair-code/federated-learning/blob/080b6b748d83aad714f7eb653d9c98158aedb6d8/src/common.ts#L30)):*
> ```XML
>   version: string,
>   clientId: string,
>   vars: Variable[]
> ```

Should the messages we send between client and server be JSON, and if so, does that mean we have to do some kind of custom serialization of variables (e.g. as `{ name: string, shape: number[], values: number[], dtype: string }`)? Or does TensorflowJS support that out of the box?

---

*[src/common.ts, line 36 at r1](https://reviewable.io/reviews/pair-code/federated-learning/3#-LEPd0sH8O9v3L71jE-X:-LEPd0sH8O9v3L71jE-Y:by5e89i) ([raw file](https://github.com/pair-code/federated-learning/blob/080b6b748d83aad714f7eb653d9c98158aedb6d8/src/common.ts#L36)):*
> ```XML
>   clientId: string,
>   fitConfig: ModelFitConfig,
>   version: string,
> ```

Maybe we can rename `version` to `modelId` for clarity / symmetry with `clientId`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/pair-code/federated-learning/3)*

**Comment by asross** [comment]
Review status: 6 of 7 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[src/common.ts, line 30 at r1](https://reviewable.io/reviews/pair-code/federated-learning/3#-LEPbiab9_HfM7FEdUjn:-LEPf11T65ugzxBwlD-3:b-fl0gnf) ([raw file](https://github.com/pair-code/federated-learning/blob/080b6b748d83aad714f7eb653d9c98158aedb6d8/src/common.ts#L30)):*
<details><summary><i>Previously, asross (Andrew Ross) wrote…</i></summary><blockquote>

Should the messages we send between client and server be JSON, and if so, does that mean we have to do some kind of custom serialization of variables (e.g. as `{ name: string, shape: number[], values: number[], dtype: string }`)? Or does TensorflowJS support that out of the box?
</blockquote></details>

Also, this won't be super robust to adversaries, but one of the federated learning algorithms suggests also sending the number of examples that each local model used to generate the updates (so we can do a weighted average on the server).

---


*Comments from [Reviewable](https://reviewable.io/reviews/pair-code/federated-learning/3)*

**Comment by aman-tiwari** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/common.ts, line 30 at r1](https://reviewable.io/reviews/pair-code/federated-learning/3#-LEPbiab9_HfM7FEdUjn:-LEPorbP10qXT0nFMZad:b49iyo7) ([raw file](https://github.com/pair-code/federated-learning/blob/080b6b748d83aad714f7eb653d9c98158aedb6d8/src/common.ts#L30)):*
<details><summary><i>Previously, asross (Andrew Ross) wrote…</i></summary><blockquote>

Also, this won't be super robust to adversaries, but one of the federated learning algorithms suggests also sending the number of examples that each local model used to generate the updates (so we can do a weighted average on the server).
</blockquote></details>

1. I think socket does it into JSON but not sure how well a tf.Variable can survive being baked to JSON. I can write something in common to do this if it doesn't. Eventually we might want to use socket.io-msgpack or proto to do binary serialisation since websocket supports it.

2. Sounds good. 

---

*[src/common.ts, line 36 at r1](https://reviewable.io/reviews/pair-code/federated-learning/3#-LEPd0sH8O9v3L71jE-X:-LEPomz9E6KzTAB2BPJN:b-896fix) ([raw file](https://github.com/pair-code/federated-learning/blob/080b6b748d83aad714f7eb653d9c98158aedb6d8/src/common.ts#L36)):*
<details><summary><i>Previously, asross (Andrew Ross) wrote…</i></summary><blockquote>

Maybe we can rename `version` to `modelId` for clarity / symmetry with `clientId`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/pair-code/federated-learning/3)*

**Comment by aman-tiwari** [comment]
Review status: 2 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/common.ts, line 30 at r1](https://reviewable.io/reviews/pair-code/federated-learning/3#-LEPbiab9_HfM7FEdUjn:-LEQdlcuE-G790xO4xdW:b-896fix) ([raw file](https://github.com/pair-code/federated-learning/blob/080b6b748d83aad714f7eb653d9c98158aedb6d8/src/common.ts#L30)):*
<details><summary><i>Previously, aman-tiwari (Aman Tiwari) wrote…</i></summary><blockquote>

1. I think socket does it into JSON but not sure how well a tf.Variable can survive being baked to JSON. I can write something in common to do this if it doesn't. Eventually we might want to use socket.io-msgpack or proto to do binary serialisation since websocket supports it.

2. Sounds good. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/pair-code/federated-learning/3)*

**Comment by aman-tiwari** [comment]
LGTM

**Comment by asross** [comment]
:lgtm_strong:

---

Review status: 2 of 8 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/pair-code/federated-learning/3#-:-LEQfbKI8Dzvto72QAx9:b-jbsf8z)*

**Comment by aman-tiwari** [comment]
Dismissed @asross from 2 discussions.
Review status: 2 of 8 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/pair-code/federated-learning/3)*

**Comment by aman-tiwari** [comment]
Reviewed 2 of 7 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/pair-code/federated-learning/3)*

**Comment by aman-tiwari** [comment]
:lgtm_strong: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/pair-code/federated-learning/3#-:-LEQgWgJBPiz27FmdNkz:b-yncq6h)*

**Pull request merged**
