### PR TITLE
update server/client/model interfaces

### PR DESCRIPTION
**Pull request by asross**
This is a WIP pull request is relative to the `audio` branch, which will definitely break the MNIST and CIFAR experiments. I'm making this PR separate from the audio changes / larger reorganization to solicit feedback on the API changes alone.

The main changes are:
- the client API now handles fitting the model, and details like `numExamples` no longer need to be managed by users
- `FederatedModel` now has a simpler interface and can more transparently wrap `tf.Model`

Just as I'm making this, I can think of a few opportunities to simplify the interface even further, but I'll elaborate in comments on the diff.

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/federated-learning/15)

### CODE REVIEW

**Comment by asross** [comment]
*[audio_demo/index.js, line 81 at r1](https://reviewable.io/reviews/pair-code/federated-learning/15#-LGQas6t8LM-jYGAG2cT:-LGQas6t8LM-jYGAG2cU:b-h495ya) ([raw file](https://github.com/pair-code/federated-learning/blob/705b876eb964df875abd14764e000ef63698e1d2/audio_demo/index.js#L81)):*
> ```JavaScript
> 
> fedModel.setup().then(async () => {
>   const model = fedModel.model;
> ```

This is still awkward -- although it's nice to be able to access the underlying `tf.Model` (and maybe we'll still need to in order to compute the input shape), we shouldn't have to for things like prediction.

---


*Comments from [Reviewable](https://reviewable.io/reviews/pair-code/federated-learning/15)*

**Comment by asross** [comment]
*[audio_demo/index.js, line 92 at r1](https://reviewable.io/reviews/pair-code/federated-learning/15#-LGQbHmU1HVX8JqtT4DZ:-LGQbHmU1HVX8JqtT4D_:b-upbays) ([raw file](https://github.com/pair-code/federated-learning/blob/705b876eb964df875abd14764e000ef63698e1d2/audio_demo/index.js#L92)):*
> ```JavaScript
>     modelVersion.innerText = msg.modelId;
>   });
>   await clientAPI.setup(serverURL);
> ```

Instead of calling `fedModel.setup` and then `clientAPI.setup`, maybe the client API should mimic the server API and accept an uninitialized FederatedModel, but have _it's_ `setup` method initialize both itself and the federated model. So basically, this code would look like this instead:

```js
const serverURL = 'http://foo.bar';
const model = new AudioTransferLearningModel();
const api = new ClientAPI(model, serverURL);
api.setup().then(() => {
  // rest of logic
});
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/pair-code/federated-learning/15)*

**Comment by asross** [comment]
*[src/client/comm.ts, line 131 at r1](https://reviewable.io/reviews/pair-code/federated-learning/15#-LGQbxpvB_gqnQOzIB55:-LGQbxpvB_gqnQOzIB56:b-cdxfq1) ([raw file](https://github.com/pair-code/federated-learning/blob/705b876eb964df875abd14764e000ef63698e1d2/src/client/comm.ts#L131)):*
> ```XML
>    * TODO: consider having this method save copies of `xs` and `ys` when there
>    * are too few examples, and only doing training/uploading after reaching a
>    * configurable threshold (disposing of the copies afterwards).
> ```

Interested in feedback on the idea laid out in this comment -- might be a nice way of delaying updates until we get sufficient data without forcing the user to deal with that complexity. Not sure what the best way to transmit that configuration is, though.

---


*Comments from [Reviewable](https://reviewable.io/reviews/pair-code/federated-learning/15)*

**Comment by asross** [comment]
*[src/client/comm.ts, line 140 at r1](https://reviewable.io/reviews/pair-code/federated-learning/15#-LGQcJa8-NtCKsuyAP8b:-LGQcJa8-NtCKsuyAP8c:b-euqdcw) ([raw file](https://github.com/pair-code/federated-learning/blob/705b876eb964df875abd14764e000ef63698e1d2/src/client/comm.ts#L140)):*
> ```XML
>     const modelId = this.msg.modelId;
>     // fit the model to the new data
>     await this.model.fit(xs, ys, this.msg.fitConfig);
> ```

One thing I realized while writing this is that `ModelFitConfig` doesn't let you pass options to your optimizer (like the learning rate). For now it's probably fine if that stays fixed, but it would be nice if the server could dynamically set clients' learning rates through `fitConfig`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/pair-code/federated-learning/15)*

**Comment by aman-tiwari** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[audio_demo/index.js, line 81 at r1](https://reviewable.io/reviews/pair-code/federated-learning/15#-LGQas6t8LM-jYGAG2cT:-LGQcgnr8j-fF_w57uR6:b-2j29ae) ([raw file](https://github.com/pair-code/federated-learning/blob/705b876eb964df875abd14764e000ef63698e1d2/audio_demo/index.js#L81)):*
<details><summary><i>Previously, asross (Andrew Ross) wrote…</i></summary><blockquote>

This is still awkward -- although it's nice to be able to access the underlying `tf.Model` (and maybe we'll still need to in order to compute the input shape), we shouldn't have to for things like prediction.
</blockquote></details>

You could cleanly do this as 
```js
fedModel.setup().then(async ({ model }) => {
 ...
})```

Or
```js
fedModel.setup().then(async ({ model: unwrappedModel }) => {
```

etc

---

*[src/client/comm.ts, line 131 at r1](https://reviewable.io/reviews/pair-code/federated-learning/15#-LGQbxpvB_gqnQOzIB55:-LGQdw3yCh-Jm6GrgSyg:b-h41ckm) ([raw file](https://github.com/pair-code/federated-learning/blob/705b876eb964df875abd14764e000ef63698e1d2/src/client/comm.ts#L131)):*
<details><summary><i>Previously, asross (Andrew Ross) wrote…</i></summary><blockquote>

Interested in feedback on the idea laid out in this comment -- might be a nice way of delaying updates until we get sufficient data without forcing the user to deal with that complexity. Not sure what the best way to transmit that configuration is, though.
</blockquote></details>

Does reverting to the same weights give us better loss (e.g so that the clients don't diverge too much if the syncs are slow/don't run ahead of each other too much)? Does this also mean if a user is sufficiently multimodal data (w/ modality correlated with time) a single user gets to act as multiple clients.

---

*[src/client/comm.ts, line 140 at r1](https://reviewable.io/reviews/pair-code/federated-learning/15#-LGQcJa8-NtCKsuyAP8b:-LGQxok01krXeSpacumq:by4k2qe) ([raw file](https://github.com/pair-code/federated-learning/blob/705b876eb964df875abd14764e000ef63698e1d2/src/client/comm.ts#L140)):*
<details><summary><i>Previously, asross (Andrew Ross) wrote…</i></summary><blockquote>

One thing I realized while writing this is that `ModelFitConfig` doesn't let you pass options to your optimizer (like the learning rate). For now it's probably fine if that stays fixed, but it would be nice if the server could dynamically set clients' learning rates through `fitConfig`.
</blockquote></details>

Perhaps if we keep needing to add things like this it might be worth creating a `FederatedOptimiser` class that handles it.

---

*[src/client/comm.ts, line 167 at r1](https://reviewable.io/reviews/pair-code/federated-learning/15#-LGQxQ_d7bm-R23R61Q5:-LGQxQ_d7bm-R23R61Q6:bdo22jm) ([raw file](https://github.com/pair-code/federated-learning/blob/705b876eb964df875abd14764e000ef63698e1d2/src/client/comm.ts#L167)):*
> ```XML
>   protected setVarsFromMessage(newVars: SerializedVariable[]) {
>     tf.tidy(() => {
>       this.model.setVars(newVars.map(deserializeVar));
> ```

Minor (very minor) : try `.map(v => deserializeVar(v))` because if we ever change `deserializeVar` to take more than 1 argument it'll break here as map calls the mapper function with `(value, index, array)` rather than just `value`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/pair-code/federated-learning/15)*

**Comment by dsmilkov** [comment]
This is really nice simplification! Left a few comments. Feel free to come chat in person (much faster) if you have any questions

---

Reviewed 7 of 8 files at r1.
Review status: 0 of 1 LGTMs obtained

---

*[audio_demo/index.js, line 81 at r1](https://reviewable.io/reviews/pair-code/federated-learning/15#-LGQas6t8LM-jYGAG2cT:-LGR2R7x3sHaZybg2Hcw:bhteosj) ([raw file](https://github.com/pair-code/federated-learning/blob/705b876eb964df875abd14764e000ef63698e1d2/audio_demo/index.js#L81)):*
<details><summary><i>Previously, aman-tiwari (Aman Tiwari) wrote…</i></summary><blockquote>

You could cleanly do this as 
```js
fedModel.setup().then(async ({ model }) => {
 ...
})```

Or
```js
fedModel.setup().then(async ({ model: unwrappedModel }) => {
```

etc
</blockquote></details>

Require that the user passes a tf.Model in the c-tor of `FederatedTfModel` (and therefore in the c-tor of AudioTransferLearningModel) and make FederatedTfModel.model private

---

*[audio_demo/index.js, line 92 at r1](https://reviewable.io/reviews/pair-code/federated-learning/15#-LGQbHmU1HVX8JqtT4DZ:-LGQfbbW5Zdqv2OdpydN:b-8pj45z) ([raw file](https://github.com/pair-code/federated-learning/blob/705b876eb964df875abd14764e000ef63698e1d2/audio_demo/index.js#L92)):*
<details><summary><i>Previously, asross (Andrew Ross) wrote…</i></summary><blockquote>

Instead of calling `fedModel.setup` and then `clientAPI.setup`, maybe the client API should mimic the server API and accept an uninitialized FederatedModel, but have _it's_ `setup` method initialize both itself and the federated model. So basically, this code would look like this instead:

```js
const serverURL = 'http://foo.bar';
const model = new AudioTransferLearningModel();
const api = new ClientAPI(model, serverURL);
api.setup().then(() => {
  // rest of logic
});
```

</blockquote></details>

This is really nice - removes the need for 2 setup() calls. I would do `api.connect()` instead of `api.setup()`. In this case, you don't need TF

---

*[src/comm_test.ts, line 111 at r1](https://reviewable.io/reviews/pair-code/federated-learning/15#-LGR1ShRBhYzgRU93AjP:-LGR1ShRBhYzgRU93AjQ:b4r0utq) ([raw file](https://github.com/pair-code/federated-learning/blob/705b876eb964df875abd14764e000ef63698e1d2/src/comm_test.ts#L111)):*
> ```XML
> 
>   it('transmits fit config on startup', () => {
>     expect(clientAPI.msg.fitConfig.batchSize).toBe(batchSize);
> ```

instead of reading the `msg` field (which should be private), how about calling onUpdate() and make sure it gets called with the right batchSize

---

*[src/comm_test.ts, line 147 at r1](https://reviewable.io/reviews/pair-code/federated-learning/15#-LGR1eB1ENybfOax-vX0:-LGR1eB1ENybfOax-vX1:b-6slcjg) ([raw file](https://github.com/pair-code/federated-learning/blob/705b876eb964df875abd14764e000ef63698e1d2/src/comm_test.ts#L147)):*
> ```XML
>     await clientAPI.federatedUpdate(dummyX3, dummyY);
> 
>     waitUntil(() => clientAPI.msg.modelId !== modelId, () => {
> ```

Now that you have `onUpdate()` and `msg` field being private (see previous comment), no need to do waitUntil(). Test the public API instead by subscribing via calling `onUpdate()`

---

*[src/types.ts, line 25 at r1](https://reviewable.io/reviews/pair-code/federated-learning/15#-LGR-IehC5K_3gCZQ9nq:-LGR-IehC5K_3gCZQ9nr:b-qbamei) ([raw file](https://github.com/pair-code/federated-learning/blob/705b876eb964df875abd14764e000ef63698e1d2/src/types.ts#L25)):*
> ```XML
> 
> export interface FederatedModel {
>   setup(): Promise<void>;
> ```

let's add some short jsdocs to these methods , since this is public api.

---

*[src/client/comm.ts, line 55 at r1](https://reviewable.io/reviews/pair-code/federated-learning/15#-LGR1EGx8UFzd7wcveMf:-LGR1EGx8UFzd7wcveMg:b-1hlvp0) ([raw file](https://github.com/pair-code/federated-learning/blob/705b876eb964df875abd14764e000ef63698e1d2/src/client/comm.ts#L55)):*
> ```XML
>  */
> 
> type UpdateCallback = (msg: DownloadMsg) => void;
> ```

how about renaming DownloadMsg to ClientUpdateMsg to be more explicit?

---

*[src/client/comm.ts, line 59 at r1](https://reviewable.io/reviews/pair-code/federated-learning/15#-LGR0p1H0QIIxreC6FT3:-LGR0p1H0QIIxreC6FT4:b-mkf7ti) ([raw file](https://github.com/pair-code/federated-learning/blob/705b876eb964df875abd14764e000ef63698e1d2/src/client/comm.ts#L59)):*
> ```XML
> export class ClientAPI {
>   public model: FederatedModel;
>   public msg: DownloadMsg;
> ```

make this `msg` field private? since there is no reason the user will need this. They have onUpdate() method to subscribe to these messages.

---

*[src/client/comm.ts, line 131 at r1](https://reviewable.io/reviews/pair-code/federated-learning/15#-LGQbxpvB_gqnQOzIB55:-LGR7UF74G9hqrKRb4ru:b-k0r73q) ([raw file](https://github.com/pair-code/federated-learning/blob/705b876eb964df875abd14764e000ef63698e1d2/src/client/comm.ts#L131)):*
<details><summary><i>Previously, aman-tiwari (Aman Tiwari) wrote…</i></summary><blockquote>

Does reverting to the same weights give us better loss (e.g so that the clients don't diverge too much if the syncs are slow/don't run ahead of each other too much)? Does this also mean if a user is sufficiently multimodal data (w/ modality correlated with time) a single user gets to act as multiple clients.
</blockquote></details>

Let's leave it for now (Having the TODO there is great). Finding the right balance between magic vs user-control will be easier to find once we have a few experiments.

---

*[src/client/comm.ts, line 140 at r1](https://reviewable.io/reviews/pair-code/federated-learning/15#-LGQcJa8-NtCKsuyAP8b:-LGR6659E-U7L4MEQTPY:b-r4qkpu) ([raw file](https://github.com/pair-code/federated-learning/blob/705b876eb964df875abd14764e000ef63698e1d2/src/client/comm.ts#L140)):*
<details><summary><i>Previously, aman-tiwari (Aman Tiwari) wrote…</i></summary><blockquote>

Perhaps if we keep needing to add things like this it might be worth creating a `FederatedOptimiser` class that handles it.
</blockquote></details>

If I understand correctly, `fitConfig` is a dictionary that the user fully controls right? Meaning the user passes this obj when constructing the ServerAPI, and later gets it on the other side in the ClientAPI. Then there is no reason to explicitly constraint it. You can type it as {[key: string] => any}

---


*Comments from [Reviewable](https://reviewable.io/reviews/pair-code/federated-learning/15#-:-LGR8D6g6x67IJ8mOPwr:bh8o8fc)*

**Comment by asross** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[src/client/comm.ts, line 55 at r1](https://reviewable.io/reviews/pair-code/federated-learning/15#-LGR1EGx8UFzd7wcveMf:-LGRiMPLBf8x7pDdQAJ8:b2yby1s) ([raw file](https://github.com/pair-code/federated-learning/blob/705b876eb964df875abd14764e000ef63698e1d2/src/client/comm.ts#L55)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

how about renaming DownloadMsg to ClientUpdateMsg to be more explicit?
</blockquote></details>

So... in the changes I just pushed up, I ended up doubling down(loads); i.e. changing `UpdateCallback` to `DownloadCallback` rather than changing `DownloadMsg` to `ClientUpdateMsg`. This makes it so we consistently use `Download`/`Upload` to refer to server-to-client/client-to-server communication everywhere in the codebase, which I think addresses the problem. But if we want to gsub `Download` and `Upload` for other terms, I'd be ok with that too!

---

*[src/client/comm.ts, line 131 at r1](https://reviewable.io/reviews/pair-code/federated-learning/15#-LGQbxpvB_gqnQOzIB55:-LGRgtwMAwMebmV_dT0D:b-witrdo) ([raw file](https://github.com/pair-code/federated-learning/blob/705b876eb964df875abd14764e000ef63698e1d2/src/client/comm.ts#L131)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

Let's leave it for now (Having the TODO there is great). Finding the right balance between magic vs user-control will be easier to find once we have a few experiments.
</blockquote></details>

@aman-tiwari yep -- reverting to the same weights means that one user gets to act as multiple clients, which is already true on the server side. If we _didn't_ revert, then users would be sending us multiple updates for the same data points, and the first data point they happened to see would be overemphasized relative to the last one.

There are compelling reasons against reverting too; e.g. if server downloads are few and far between, and we want clients to improve locally in the interim. But there are potential downsides too. I summarized some of the pros and cons in https://github.com/PAIR-code/federated-learning/issues/7.

---


*Comments from [Reviewable](https://reviewable.io/reviews/pair-code/federated-learning/15)*

**Comment by asross** [comment]
*[src/serialization.ts, line 68 at r2](https://reviewable.io/reviews/pair-code/federated-learning/15#-LGRjX490nwdJnl_dY2s:-LGRjX490nwdJnl_dY2t:b-ssidkd) ([raw file](https://github.com/pair-code/federated-learning/blob/2298b7c17411fb05c5ecc5b3ee8899ebab276efd/src/serialization.ts#L68)):*
> ```XML
>   numExamples: number,
>   vars: TensorJson[],
>   modelVersion?: string,
> ```

I ended up renaming `modelId` to `modelVersion` just because that's how it felt most natural to refer to it on the client side, and since it is a monotonically increasing timestamp, I think it's an appropriate name.

---


*Comments from [Reviewable](https://reviewable.io/reviews/pair-code/federated-learning/15)*

**Comment by asross** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[src/types.ts, line 30 at r2](https://reviewable.io/reviews/pair-code/federated-learning/15#-LGRjrNw2mCMT7Vw0z1Y:-LGRjrNw2mCMT7Vw0z1Z:b-b8pn25) ([raw file](https://github.com/pair-code/federated-learning/blob/2298b7c17411fb05c5ecc5b3ee8899ebab276efd/src/types.ts#L30)):*
> ```XML
> }
> 
> export class FederatedTfModel implements FederatedModel {
> ```

Part of me wants to rename `FederatedTfModel` to just `Federated`, so we can write code like:
```js
const model = await tf.loadModel(url);
const fedModel = Federated(model);
```
But that might be too cute / less clear.

---


*Comments from [Reviewable](https://reviewable.io/reviews/pair-code/federated-learning/15)*

**Comment by dsmilkov** [comment]
:lgtm_strong: Nice!!

---

Reviewed 1 of 8 files at r1, 9 of 11 files at r2, 2 of 2 files at r3.
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---

*[src/serialization.ts, line 68 at r2](https://reviewable.io/reviews/pair-code/federated-learning/15#-LGRjX490nwdJnl_dY2s:-LGWds2c3fFh-ljj6atM:brxp9sq) ([raw file](https://github.com/pair-code/federated-learning/blob/2298b7c17411fb05c5ecc5b3ee8899ebab276efd/src/serialization.ts#L68)):*
<details><summary><i>Previously, asross (Andrew Ross) wrote…</i></summary><blockquote>

I ended up renaming `modelId` to `modelVersion` just because that's how it felt most natural to refer to it on the client side, and since it is a monotonically increasing timestamp, I think it's an appropriate name.
</blockquote></details>

Sounds good.

---

*[src/types.ts, line 30 at r2](https://reviewable.io/reviews/pair-code/federated-learning/15#-LGRjrNw2mCMT7Vw0z1Y:-LGWeDExDvNjiczDoF0P:b-1gr9cb) ([raw file](https://github.com/pair-code/federated-learning/blob/2298b7c17411fb05c5ecc5b3ee8899ebab276efd/src/types.ts#L30)):*
<details><summary><i>Previously, asross (Andrew Ross) wrote…</i></summary><blockquote>

Part of me wants to rename `FederatedTfModel` to just `Federated`, so we can write code like:
```js
const model = await tf.loadModel(url);
const fedModel = Federated(model);
```
But that might be too cute / less clear.
</blockquote></details>

Not for this PR: I can imagine having a free-floating function `fromTFModel` instead of a public constructor, which is very js style. For example, when this is all done:

```ts
import * as client from '@tensorflow/federated-client';
const clientApi = client.fromTFModel(model);
// The intermediate FederatedTFModel object is not exposed.
...
```

---

*[src/client/comm.ts, line 55 at r1](https://reviewable.io/reviews/pair-code/federated-learning/15#-LGR1EGx8UFzd7wcveMf:-LGWg3NEAXG3WlgPWhdz:bf9l9ot) ([raw file](https://github.com/pair-code/federated-learning/blob/705b876eb964df875abd14764e000ef63698e1d2/src/client/comm.ts#L55)):*
<details><summary><i>Previously, asross (Andrew Ross) wrote…</i></summary><blockquote>

So... in the changes I just pushed up, I ended up doubling down(loads); i.e. changing `UpdateCallback` to `DownloadCallback` rather than changing `DownloadMsg` to `ClientUpdateMsg`. This makes it so we consistently use `Download`/`Upload` to refer to server-to-client/client-to-server communication everywhere in the codebase, which I think addresses the problem. But if we want to gsub `Download` and `Upload` for other terms, I'd be ok with that too!
</blockquote></details>

Sounds good! +1 to having consistency between the type and the subscribing method name,

---

*[src/client/comm.ts, line 57 at r3](https://reviewable.io/reviews/pair-code/federated-learning/15#-LGWgLij2JHtsWdCkyjN:-LGWgLij2JHtsWdCkyjO:b4widgb) ([raw file](https://github.com/pair-code/federated-learning/blob/2649915a8c3017d89be1472215dbe114ace264ec/src/client/comm.ts#L57)):*
> ```XML
>    * Construct a client API for federated learning that will push and pull
>    * `model` updates from the server.
>    * @param {model<FederatedModel>} model - model to use with federated learning
> ```

no need for closure style annotation (remove `{model<FederatedModel>} ` after `@param`

---


*Comments from [Reviewable](https://reviewable.io/reviews/pair-code/federated-learning/15#-:-LGWgxwR3bAt8RDUAphP:b-6wt3w0)*

**Comment by asross** [comment]
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---

*[src/types.ts, line 30 at r2](https://reviewable.io/reviews/pair-code/federated-learning/15#-LGRjrNw2mCMT7Vw0z1Y:-LGWi-9t5iO9qQ2G-8SD:b-qhp7t1) ([raw file](https://github.com/pair-code/federated-learning/blob/2298b7c17411fb05c5ecc5b3ee8899ebab276efd/src/types.ts#L30)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

Not for this PR: I can imagine having a free-floating function `fromTFModel` instead of a public constructor, which is very js style. For example, when this is all done:

```ts
import * as client from '@tensorflow/federated-client';
const clientApi = client.fromTFModel(model);
// The intermediate FederatedTFModel object is not exposed.
...
```


</blockquote></details>

Yep, that would work well! In the next PR I modified the client/server APIs to take either a `FederatedModel` or a `tf.Model`, which feels very natural as well!

---

*[src/client/comm.ts, line 57 at r3](https://reviewable.io/reviews/pair-code/federated-learning/15#-LGWgLij2JHtsWdCkyjN:-LGWhmgb6DUdv7Qt2a-h:b-t8mimk) ([raw file](https://github.com/pair-code/federated-learning/blob/2649915a8c3017d89be1472215dbe114ace264ec/src/client/comm.ts#L57)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

no need for closure style annotation (remove `{model<FederatedModel>} ` after `@param`
</blockquote></details>

Sounds good. Will fix in next PR to avoid merge conflicts (which will be arriving just after this gets merged)

---


*Comments from [Reviewable](https://reviewable.io/reviews/pair-code/federated-learning/15)*

**Pull request merged**
